name = "gleam_json"
version = "2.0.0"
gleam = ">= 0.32.0"

licences = ["Apache-2.0"]
description = "Work with JSON in Gleam"

repository = { type = "github", user = "gleam-lang", repo = "json" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.19.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
