name = "gleam_json"
version = "0.5.0"
licences = ["Apache-2.0"]
description = "Work with JSON in Gleam"

repository = { type = "github", user = "gleam-lang", repo = "json" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.19"
thoas = "~> 0.2"

[dev-dependencies]
gleeunit = "~> 0.6"
